---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.itchallenge.fr
  resources:
  - scalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.itchallenge.fr
  resources:
  - scalers/finalizers
  verbs:
  - update
- apiGroups:
  - api.itchallenge.fr
  resources:
  - scalers/status
  verbs:
  - get
  - patch
  - update
